/*
    This file is part of the iText (R) project.
    Copyright (c) 1998-2020 iText Group NV
    Authors: iText Software.

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License version 3
    as published by the Free Software Foundation with the addition of the
    following permission added to Section 15 as permitted in Section 7(a):
    FOR ANY PART OF THE COVERED WORK IN WHICH THE COPYRIGHT IS OWNED BY
    ITEXT GROUP. ITEXT GROUP DISCLAIMS THE WARRANTY OF NON INFRINGEMENT
    OF THIRD PARTY RIGHTS

    This program is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
    or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.
    You should have received a copy of the GNU Affero General Public License
    along with this program; if not, see http://www.gnu.org/licenses or write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA, 02110-1301 USA, or download the license from the following URL:
    http://itextpdf.com/terms-of-use/

    The interactive user interfaces in modified source and object code versions
    of this program must display Appropriate Legal Notices, as required under
    Section 5 of the GNU Affero General Public License.

    In accordance with Section 7(b) of the GNU Affero General Public License,
    a covered work must retain the producer line in every PDF that is created
    or manipulated using iText.

    You can be released from the requirements of the license by purchasing
    a commercial license. Buying such a license is mandatory as soon as you
    develop commercial activities involving the iText software without
    disclosing the source code of your own applications.
    These activities include: offering paid services to customers as an ASP,
    serving PDFs on the fly in a web application, shipping iText with a closed
    source product.

    For more information, please contact iText Software Corp. at this
    address: sales@itextpdf.com
 */
package com.itextpdf.pdfdebug.netbeans;

import com.itextpdf.kernel.PdfException;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfReader;
import com.itextpdf.rups.Rups;
import com.itextpdf.rups.event.RupsEvent;

import com.itextpdf.rups.model.LoggerHelper;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;
import javax.swing.SwingUtilities;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays RUPS
 */
@ConvertAsProperties(
        dtd = "-//com.itextpdf.pdfdebug.netbeans//RUPS//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "RUPSTopComponent",
        iconBase = "com/itextpdf/pdfdebug/netbeans/pdfdebug.png",
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "navigator", openAtStartup = false)
@ActionID(category = "Window", id = "com.itextpdf.pdfdebug.netbeans.RUPSTopComponent")
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_RUPSAction",
        preferredID = "RUPSTopComponent"
)
@Messages({
    "CTL_RUPSAction=RUPS",
    "CTL_RUPSTopComponent=PDF Debug",
    "HINT_RUPSTopComponent=This is a PDF Debug window"
})
public final class RUPSTopComponent extends TopComponent {

    private volatile Rups rups = null;

    private volatile PdfDocument prevDoc = null;
    public byte[] documentRawBytes = null;
    private String variableName = "";
    private final Observer observeRupsEvent = new Observer() {
        @Override
        public void update(Observable o, final Object arg) {
            if (arg instanceof RupsEvent) {
                RupsEvent event = (RupsEvent) arg;
                if (event.getType() == RupsEvent.OPEN_DOCUMENT_POST_EVENT) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            rups.highlightLastSavedChanges();
                            rups.unregisterEventObserver(observeRupsEvent);
                        }

                    });
                    
                }
            }
        }
    };

    public RUPSTopComponent() {
        initComponents();
        setName(Bundle.CTL_RUPSTopComponent());
        setToolTipText(Bundle.HINT_RUPSTopComponent());
        initRups();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void initRups() {
        jPanel1.setLayout(new BorderLayout());
        final Dimension dim = new Dimension(400, 400);
        rups = Rups.startNewPlugin(jPanel1, dim, null);
    }

    public void loadAndHighlightRups() {
        ByteArrayInputStream bais = null;
        try {
            if (documentRawBytes != null) {
                bais = new ByteArrayInputStream(documentRawBytes);
                PdfReader reader = new PdfReader(bais);
                PdfDocument tempDoc = new PdfDocument(reader);
                boolean isEqual = false;
                if (prevDoc != null) {
                    isEqual = rups.compareWithDocument(tempDoc, true);
                }
                if (!isEqual) {
                    if (prevDoc != null) {
                        rups.registerEventObserver(observeRupsEvent);
                    }
                    rups.loadDocumentFromRawContent(documentRawBytes, variableName, null, true);
                } else if (prevDoc != null) {
                    rups.highlightLastSavedChanges();
                }

                prevDoc = tempDoc;
            }
        } catch (final IOException | PdfException | com.itextpdf.io.IOException e) {
            LoggerHelper.error("Error while reading pdf file.", e, getClass());
        } catch (final Exception e) {
            LoggerHelper.error("Unexpected error.", e, getClass());
        } finally {
            try {
                if (bais != null) {
                    bais.close();
                }
            } catch (IOException ignored) {
            }
        }
    }

    public void disposePdfWindow() {
        try {
            rups.clearHighlights();
            rups.closeDocument();
            if (prevDoc != null) {
                prevDoc.close();
                prevDoc = null;
            }
        } catch (Exception any) {
            LoggerHelper.error("Closing error.", any, getClass());
        }
    }

    void setDocumentRawBytes(byte[] rawBytes) {
        documentRawBytes = rawBytes;
    }

    void setVariableName(String name) {
        variableName = name;
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
